USE school;
CREATE TABLE HOME(HOME_ID INT(10),HOME_NAME VARCHAR(20),OWNER_NAME VARCHAR(20),ADDRESS VARCHAR(40),HOME_NO INT(10),OWNER_NO BIGINT(20),NO_OF_MEMBERS INT(20),NO_OF_WINDOW BIGINT(40));
CREATE TABLE HOTEK(HOTEL_NAME VARCHAR(20),OWNER_NAME VARCHAR(20),ADDRESS VARCHAR(40),HOTEL_NO INT(10),OWNER_NO BIGINT(20),NO_OF_DISHES INT(20),INCOME BIGINT(40));
CREATE TABLE SHOPPING(SHOPPING_ID INT(10),PERSON_NAME VARCHAR(10),PERSON_ADDRESS VARCHAR(10),ITEM VARCHAR(10),PHONE_NO BIGINT(10),PAYMENT BIGINT(10),AMOUMT INT(10));
CREATE TABLE COLLEGE(COLLEGE_ID INT(10),COLLEGE_NAME VARCHAR(10),COLLEGE_ADDRESS VARCHAR(10),BRANCHES VARCHAR(10),PHONE_NO BIGINT(10),FEES BIGINT(10),FACULTY INT(10));
ALTER TABLE SHOPPING ADD COLUMN CLOTH_BRAND VARCHAR(10);
SELECT * FROM SHOPPING;
ALTER TABLE SHOPPING ADD COLUMN DISCOUNT VARCHAR(10);
ALTER TABLE SHOPPING ADD COLUMN STATUS VARCHAR(10);
SELECT * FROM SHOPPING;
DESC SHOPPING;


CREATE TABLE EMPLOYEE_DETAILS(EMPLOYEE_ID VARCHAR(10),EMPLOYEE_NAME VARCHAR(30));
ALTER TABLE EMPLOYEE_DETAILS ADD COLUMN PHONE_NO bigint(10);
ALTER TABLE EMPLOYEE_DETAILS ADD COLUMN ADDRESS VARCHAR(30),ADD COLUMN POSITION VARCHAR(30), ADD COLUMN SALARY INT(30),ADD COLUMN PROJECT_TEAM VARCHAR(30);
ALTER TABLE EMPLOYEE_DETAILS DROP COLUMN SALARY,DROP COLUMN ADDRESS;
ALTER TABLE EMPLOYEE_DETAILS RENAME COLUMN EMPLOYEE_ID TO EMP_ID;
ALTER TABLE EMPLOYEE_DETAILS RENAME COLUMN EMPLOYEE_NAME TO EMP_NAME, RENAME COLUMN PHONE_NO TO PHNNO,
RENAME COLUMN POSITION TO JOB_TITLE,RENAME COLUMN PROJECT_TEAM TO TEAM_NAME;
ALTER TABLE EMPLOYEE_DETAILS MODIFY COLUMN EMP_ID INT(10);
ALTER TABLE EMPLOYEE_DETAILS MODIFY COLUMN EMP_NAME CHAR(10);
ALTER TABLE EMPLOYEE_DETAILS MODIFY COLUMN PHNNO INT(10);
ALTER TABLE EMPLOYEE_DETAILS MODIFY COLUMN JOB_TITLE CHAR(10);
ALTER TABLE EMPLOYEE_DETAILS MODIFY COLUMN TEAM_NAME CHAR(40);

CREATE TABLE AIRPORT_DETAILS(AIRPORT_NAME VARCHAR(30),ADDRESS VARCHAR(40));
ALTER TABLE AIRPORT_DETAILS ADD COLUMN NO_OF_PLANES INT(10),ADD COLUMN COMPANY VARCHAR(20),ADD COLUMN NO_OF_ENGINEERS INT(10),
ADD COLUMN CABIN_CREW VARCHAR(10), ADD COLUMN ARRIVAL VARCHAR(10);
ALTER TABLE AIRPORT_DETAILS DROP COLUMN CABIN_CREW,DROP COLUMN ADDRESS;
ALTER TABLE AIRPORT_DETAILS RENAME COLUMN AIRPORT_NAME TO AIRPORT; 
USE SCHOOL;
ALTER TABLE AIRPORT_DETAILS RENAME COLUMN AIRPORT_NAME TO AIRPORT; 


