USE HW;
CREATE TABLE ORDER(ORDER_ID INT NOT NULL PRIMARY KEY,ORDER_NAME VARCHAR(100) NOT NULL,COST INT,CREATED_AT TIMESTAMP,
CREATED_BY VARCHAR(100),MODIFIED AT TIMESTAMP,MODIFIED_BY VARCHAR(100));

CREATE TABLE PAYMENT(PAYMENT_ID INT PRIMARY KEY,PRICE INT,ORDER_ID INT,PAYMENT_STATUS VARCHAR(100),
CREATED_AT TIMESTAMP,CREATED_BY VARCHAR(100),MODIFIED AT TIMESTAMP,MODIFIED_BY VARCHAR(100), FOREIGN KEY(ORDER_ID) REFRENCES ORDER;

INSERT INTO ORDER VALUES(101,'MOBILE',60000,'ROHAN','ROHAN');
INSERT INTO ORDER VALUES(102,'LAPTOP',60000,'RAM','RAM');
INSERT INTO ORDER VALUES(103,'KEYCHAIN',60000,'MOHAN','MOHAN');
INSERT INTO ORDER VALUES(104,'TABLE',60000,'RIYA','RIYA');
INSERT INTO ORDER VALUES(105,'KITCHEN SET',60000,'NISHA','NISHA');

INSERT INTO PAYMENT VALUES(201,60000,'PAID',101,'ROHAN','ROHAN');
INSERT INTO PAYMENT VALUES(202,60000,'PENDING',101,'RAM','RAM');
INSERT INTO PAYMENT VALUES(203,60000,'PAID',101,'MOHAN','MOHAN');
INSERT INTO PAYMENT VALUES(204,60000,'PENDING',101,'RIYA','RIYA');
INSERT INTO PAYMENT VALUES(205,60000,'PAID',101,'NISHA','NISHA');


CREATE TABLE RESTAURENT(R_ID INT PRIMARY KEY,RESTAURANT_NAME VARCHAR(100),LOC VARCHAR(100),ORDER_ID INT,
RATINGS VARCHAR(10),PAYMENT_ID INT,CREATED_AT TIMESTAMP,CREATED_BY VARCHAR(100),MODIFIED AT TIMESTAMP,
MODIFIED_BY VARCHAR(100),FOREIGN KEY(ORDER_ID) PAYMENT(PAYMENT_ID));

CREATE TABLE DELIVERY(D_ID INT PRIMARY KEY,P_NAME VARCHAR(100),MOP ENUM('CASH','ONLINE'),RESTAURENT_ID INT,
CREATED_AT TIMESTAMP,CREATED_BY VARCHAR(100),MODIFIED AT TIMESTAMP,MODIFIED_BY VARCHAR(100)
FOREIGN KEY(RESTURANT_ID)REFERENCES RESTAURENT(R_ID),
FOREIGN KEY (ORDER_ID)REFERENCES ORDER(ORDER_ID));


